Added session
PXgamer/kastatus pull request #3
Opened 2016-10-20 10:21 UTC by dhwanilvyas

2016-10-20 10:55 UTC, PXgamer commented on admin/index.php
> +			<?php session_destroy() ?>
This results in being logged out when selecting an option in the admin page.

Would be better to add this as part of a new file (e.g. `/logout/index.php` that would have the following:

```php
<?php
session_destroy();
header('Location: /');
```

Or something similar, then change the logout button to link to `/logout/`.

2016-10-20 11:28 UTC, owenvoke approved these changes

2016-10-20 11:31 UTC, owenvoke requested changes

2016-10-20 11:31 UTC, PXgamer commented on admin/index.php
> +			<?php session_destroy() ?>
This results in being logged out when selecting an option in the admin page.

Would be better to add this as part of a new file (e.g. `/logout/index.php` that would have the following:

```php
<?php
session_destroy();
header('Location: /');
```

Or something similar, then change the logout button to link to `/logout/`.

2016-10-20 15:55 UTC, dhwanilvyas commented on admin/index.php
> +			<?php session_destroy() ?>
I have updated my PR.

2016-10-20 17:50 UTC, owenvoke reviewed
Seems fine, I'll test it in a bit. :smile:

2016-10-22 10:03 UTC, owenvoke approved these changes

2016-10-22 10:03 UTC, merged